<a href="https://colab.research.google.com/github/ezinneanne/DeepTechReady-Work/blob/new_branch/Week_4_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1



1.   Define Natural Language Processing (NLP) in your own words.

     Answer: Natural Language Processing(NLP) is a subset of machine learning that involves machines being able to know, interpret human communication and provide a suitable response.

2.   List at least three real-world applications of NLP and explain their significance.

     Answer: Google/Siri Assistant, Google Translate, Email spam filters. Their significance includes:
     - Providing reliable information to users, helping users perform tasks using user voice commands only.
     - Translating languages for users enabling smooth flow of communication.
     - Being able to spot out spam messages by identifying certain words in a mail head or body of the mail.

3.   Identify and explain two challenges that make NLP complex.

     Answer: Ambiguity and noisy data.

     Ambiguous words i.e words without a clear meaning can be complex for machines to understand. An example is the sentence in the course material "I saw the man with the telescope" this is ambiguous as the man is not known to the machine. Another example is "We  saw her duck", this is unclear too as the machine will struggle to understand if it was her duck or her dodging something.

     Noisy words are usually found on social media where people communicate using slangs and acronyms. Examples are "See u 2morrow" and "Tysm!". Now, these words are difficult for a machine to interpret them correctly.

In [1]:
# importing the regex library
import re

# Using re.findall() to extract email address
text = "Contact us at support@company.com or sales@business.org. For more, email info@service.net."

emails = re.findall(r'\b[\w.-]+@[\w.-]+\.\w+\b', text)

print("Emails found: ", emails)


Emails found:  ['support@company.com', 'sales@business.org', 'info@service.net']


In [2]:
# Using re.findall() to extract words that end with "ing" in a sentence
sentence = "NLP is amazing for cleaning and processing text while learning new techniques."

ing_words = re.findall(r'\b\w+ing\b', sentence)

print("Words ending with 'ing': ", ing_words)

Words ending with 'ing':  ['amazing', 'cleaning', 'processing', 'learning']


In [3]:
# A python program to clean a text by removing all punctuation, converting it to lowercase, and splitting it to words.
def clean_text(text):
    # Remove punctuation
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    # Convert to lowercase
    text = text.lower()
    # Split into words
    words = text.split()
    return words

text = "NLP makes AI smarter! But, sometimes, it’s challenging... Don’t you agree?"
cleaned_words = clean_text(text)
print("Cleaned words: ",cleaned_words)

Cleaned words:  ['nlp', 'makes', 'ai', 'smarter', 'but', 'sometimes', 'its', 'challenging', 'dont', 'you', 'agree']


# Assignment 2

In [28]:
# Applying text cleaning techniques to preprocess text
text = "OMG!! NLP is soooo coool 🤩...!!! It costs $1000. Learn it now at https://3mtt.com 😎."
# first applying lowercasing
text = text.lower()
print(text)
# second removing punctuation and links
text = re.sub(r'http\S+|www\S+', '', text)
text = re.sub(r'[^a-z\s]', '', text)
text = text.strip()
print(text)
words = text.split()
print(words)
# third removing stopwords
import nltk
from nltk.corpus import stopwords
#nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
filtered_words = [word for word in words if word not in stop_words]

def normalize_word(word):
    return re.sub(r'(.)\1+', r'\1', word)

final_words = [normalize_word(word) for word in filtered_words]

cleaned_text = " ".join(final_words)
print(cleaned_text)

omg!! nlp is soooo coool 🤩...!!! it costs $1000. learn it now at https://3mtt.com 😎.
omg nlp is soooo coool  it costs  learn it now at
['omg', 'nlp', 'is', 'soooo', 'coool', 'it', 'costs', 'learn', 'it', 'now', 'at']
omg nlp so col costs learn


In [31]:
#word tokenization
nltk.download('punkt_tab')
text = "Tokenization is the first step in NLP. It splits text into smaller pieces for analysis."
tokens = nltk.word_tokenize(text)
print(tokens)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


['Tokenization', 'is', 'the', 'first', 'step', 'in', 'NLP', '.', 'It', 'splits', 'text', 'into', 'smaller', 'pieces', 'for', 'analysis', '.']


In [32]:
#sentence tokenization
text = "Tokenization is the first step in NLP. It splits text into smaller pieces for analysis."
sentences = nltk.sent_tokenize(text)
print(sentences)

['Tokenization is the first step in NLP.', 'It splits text into smaller pieces for analysis.']


In [33]:
# using PorterStemmer
from nltk.stem import PorterStemmer

# Initialize stemmer
stemmer = PorterStemmer()

# words
words = ["running", "flies", "studies", "easily", "studying", "better"]

# Apply stemming
stemmed_words = [stemmer.stem(word) for word in words]
print("Stemmed Words:", stemmed_words)


Stemmed Words: ['run', 'fli', 'studi', 'easili', 'studi', 'better']


In [34]:
# using spacy for lemmatization
# Step 1: Upgrade pip, setuptools, and wheel
!pip install -U pip setuptools wheel

# Step 2: Install spaCy
!pip install -U spacy

# Step 3: Download the English model
!python -m spacy download en_core_web_sm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 19.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 57.2 MB/s eta 0:00:00
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.6/30.6 MB 102.7 MB/s eta 0:00:00
  Attempting uninstall: spacy
    Found existing installation: spacy 3.8.4
    Uninstalling spacy-3.8.4:
      Successfully uninstalled spacy-3.8.4
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 62.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [1]:
import spacy

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

# words
words = ["running", "flies", "studies", "easily", "studying", "better"]

# Apply lemmatization
lemmatized_words = [nlp(word)[0].lemma_ for word in words]
print("Lemmatized Words:", lemmatized_words)

Lemmatized Words: ['run', 'fly', 'study', 'easily', 'study', 'well']


# Assignment 3

In [3]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

#5 word vocabulary
vocabulary = ["anger", "sorrow", "sadness", "pity", "sympathy"]
# Converting words to numerical indices
data = np.array(vocabulary).reshape(-1, 1)

# One-Hot Encoding
encoder = OneHotEncoder(sparse_output=False)
one_hot = encoder.fit_transform(data)

print("Vocabulary:", vocabulary)
print("One-Hot Encoded Vectors:\n", one_hot)

Vocabulary: ['anger', 'sorrow', 'sadness', 'pity', 'sympathy']
One-Hot Encoded Vectors:
 [[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
#using bag of words
from sklearn.feature_extraction.text import CountVectorizer
#example dataset
dataset = ["The quick brown fox jumps over the lazy dog.", "The dog sleeps in the kernel"]

#create a BoW(bag of words) model
vectorizer = CountVectorizer()
bag_of_words = vectorizer.fit_transform(dataset)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("Bag of Words:\n", bag_of_words.toarray())

Vocabulary: ['brown' 'dog' 'fox' 'in' 'jumps' 'kernel' 'lazy' 'over' 'quick' 'sleeps'
 'the']
Bag of Words:
 [[1 1 1 0 1 0 1 1 1 0 2]
 [0 1 0 1 0 1 0 0 0 1 2]]


In [5]:
#using TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

#example dataset
dataset = ["The quick brown fox jumps over the lazy dog.", "The dog sleeps in the kernel"]

#create a TF-IDF model
vectorizer = TfidfVectorizer()
tfidf = vectorizer.fit_transform(dataset)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("TF-IDF:\n", tfidf.toarray())

Vocabulary: ['brown' 'dog' 'fox' 'in' 'jumps' 'kernel' 'lazy' 'over' 'quick' 'sleeps'
 'the']
TF-IDF:
 [[0.342369   0.24359836 0.342369   0.         0.342369   0.
  0.342369   0.342369   0.342369   0.         0.48719673]
 [0.         0.30253071 0.         0.42519636 0.         0.42519636
  0.         0.         0.         0.42519636 0.60506143]]


In [7]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 113.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 133.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 54.2 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.14.1
    Uninstalling scipy-1.14.1:
      Successfully uninstalled scipy-1.14.1


In [3]:
#using Word2Vec
from gensim.models import Word2Vec

# creating dataset of animals
animals_dataset = [["the", "dog", "barks"], ["the", "cat", "meows"], ["the", "cow", "moos"], ["the", "bird", "chirps"], ["the", "duck", "quacks"]]

# Train Word2Vec Model
word2vec_model = Word2Vec(animals_dataset, vector_size=10, window=2, min_count=1, workers=4)

# Get Embedding for a Word
print("Word Embedding for 'dog':\n", word2vec_model.wv['dog'])

Word Embedding for 'dog':
 [-0.08619688  0.03665738  0.05189884  0.05741938  0.07466918 -0.06167675
  0.01105614  0.06047282 -0.0284005  -0.06173522]


In [4]:
#loading pretrained Glove model
import gensim.downloader as api

# Load Pretrained GloVe Model
glove_model = api.load("glove-wiki-gigaword-50")

# Get Embedding for a Word
print("Word Embedding for 'king':\n", glove_model['king'])

# Find the 5 most similar words to "king"
similar_words = glove_model.most_similar('king', topn=5)
print("\nTop 5 words similar to 'king':")
for word, similarity in similar_words:
    print(f"{word}: {similarity:.4f}")

[==================================================] 100.0% 66.0/66.0MB downloaded
Word Embedding for 'king':
 [ 0.50451   0.68607  -0.59517  -0.022801  0.60046  -0.13498  -0.08813
  0.47377  -0.61798  -0.31012  -0.076666  1.493    -0.034189 -0.98173
  0.68229   0.81722  -0.51874  -0.31503  -0.55809   0.66421   0.1961
 -0.13495  -0.11476  -0.30344   0.41177  -2.223    -1.0756   -1.0783
 -0.34354   0.33505   1.9927   -0.04234  -0.64319   0.71125   0.49159
  0.16754   0.34344  -0.25663  -0.8523    0.1661    0.40102   1.1685
 -1.0137   -0.21585  -0.15155   0.78321  -0.91241  -1.6106   -0.64426
 -0.51042 ]

Top 5 words similar to 'king':
prince: 0.8236
queen: 0.7839
ii: 0.7746
emperor: 0.7736
son: 0.7667
